apiVersion : apps/v1
kind: Deployment
metadata:
  name: cdevopstechpipelinesjavascriptdocker 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cdevopstechpipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: cdevopstechpipelinesjavascriptdocker 
    spec:
      containers:
        - name: cdevopstechpipelinesjavascriptdocker 
          image: testrepo001.azurecr.io/cdevopstechpipelinesjavascriptdocker
          ports:
          - containerPort: 8080
