apiVersion : apps/v1
kind: Deployment
metadata:
  name: cdevopstechpipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdevopstechpipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: cdevopstechpipelinesjavascriptdocker 
    spec:
      containers:
        - name: cdevopstechpipelinesjavascriptdocker 
          image: testrepo01.azurecr.io/cdevopstechpipelinesjavascriptdocker
          ports:
          - containerPort: 8080